5

In [4]:
import numpy as np

P = np.array([[0, -2 / 19, -7/ 19],
             [-1 / 5, 0, -9 / 25],
             [-4 / 22, -3 / 22, 0]])
b = np.array([2,9,5])

x = np.array([0, 0, 0])
i = 1
while np.any(np.abs(P @ x + b - x) > 0.01):
    print(i)
    i += 1
    x = P @ x + b
    print(x)
print()
print(x)

1
[2. 9. 5.]
2
[-0.78947368  6.8         3.40909091]
3
[0.02822967 7.93062201 4.21626794]
4
[-0.38816419  7.47649761  3.91341888]
5
[-0.22878565  7.66880204  4.05105291]
6
[-0.2997355   7.58737808  3.99585166]
7
[-0.27082725  7.6214405   4.0198549 ]
8
[-0.28325607  7.60701769  4.00995398]

[-0.28325607  7.60701769  4.00995398]


6

In [8]:
A = np.array([[1,1,0,1,0],
              [1,0,1,0,0],
              [0,1,1,0,0],
              [1,1,1,1,0],
              [1,0,0,1,1]])

sum = np.sum(A, axis=0)
P = A / sum
print(P)

beta = 0.15
Q = (1 - beta) * P + beta / P.shape[0] * np.ones(P.shape)
x = np.ones(P.shape[0]) / P.shape[0]
for i in range(20):
    print(x)
    x = Q @ x

[[0.25       0.33333333 0.         0.33333333 0.        ]
 [0.25       0.         0.33333333 0.         0.        ]
 [0.         0.33333333 0.33333333 0.         0.        ]
 [0.25       0.33333333 0.33333333 0.33333333 0.        ]
 [0.25       0.         0.         0.33333333 1.        ]]
[0.2 0.2 0.2 0.2 0.2]
[0.18583333 0.12916667 0.14333333 0.2425     0.29916667]
[0.17479514 0.11010069 0.10720833 0.21540625 0.39248958]
[0.15937093 0.09751966 0.09157089 0.18974663 0.46179188]
[0.14525844 0.08981141 0.08357566 0.17120353 0.51015097]
[0.13482165 0.08454719 0.07912634 0.15850142 0.54300341]
[0.12751337 0.08106873 0.07637416 0.1499325  0.56511123]
[0.12254694 0.07873594 0.07460882 0.14418629 0.57992201]
[0.11920252 0.07718039 0.07344768 0.14034169 0.58982772]
[0.11696179 0.07614071 0.07267795 0.13777197 0.59644757]
[0.11546297 0.07544647 0.07216529 0.13605506 0.60087021]
[0.11446131 0.07498271 0.07182333 0.13490815 0.60382449]
[0.11379211 0.07467297 0.07159505 0.13414205 0.60579782]
[0.